services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_appTest
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel
    ports:
      - "9000:9000"

  db:
    image: postgres:16
    container_name: laravel_dbTest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Rubenmera190508
      POSTGRES_DB: practicacrud
    volumes:
      - /path/to/local/dbdata:/var/lib/postgresql/data
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: laravel_webserverTest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata: