services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_appTest
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

    networks:
      - laravel

  db:
    image: postgres:15
    container_name: laravel_dbTest
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Rubenmera190508
      POSTGRES_DB: vamos
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - laravel
  webserver:
    image: nginx:alpine
    container_name: laravel_webserverTest
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"  # Cambiar el puerto expuesto
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
