services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_appTest
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

    networks:
      - laravel
      
  webserver:
    image: nginx:alpine
    container_name: laravel_webserverTest
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"  # Cambiar el puerto expuesto
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
